### PR TITLE
Removed support for Citrix XenServer

### PR DESCRIPTION
**Pull request by FFincannon**

### CODE REVIEW

**Comment by eriweb** [comment]
The change LGTM, perhaps you could refer to the PR or some info about the change?

Also, is there a note in release notes? How should people with xenserver + nuage that upgrades handle it?

**Comment by pdion891** [comment]
Is this for a part of a particular version of CloudStack, or it never been supported?

**Comment by rafaelweingartner** [comment]
@FFincannon you mean, support of the nuage-plugin for XenServer, right?
I think the PR title is a little misleading. When I read I thought it was support of ACS for the XenServer.

**Comment by FFincannon** [comment]
Yes, Rafael, I did mean support of the Nuage plugin for XenServer.

In answer to Erik Weber's question, "How should people with xenserver +
nuage that upgrades handle it?" the product manager, Sanjeev Singh, says: "As
of now we do not have any customers on Xen and do not see any customer
demand for that. If we do see customer traction - we will re-evaluate Xen
support."

Thank you,

​Fiona

**Comment by rafaelweingartner** [comment]
The changes here seemed to have been applied in some other PR. I will close this one then.

**Pull request closed without merging**
