### PR TITLE
Updating The Nuage VSP Plugin Documentation for ACS 4.10 release

### PR DESCRIPTION
**Pull request by krissterckx**

### CODE REVIEW

**Comment by prashanthvarma** [comment]
These changes in the documentation are in accordance with our merged feature support (including bug fix) PRs. Here are some of our merged feature support PRs:

https://github.com/apache/cloudstack/pull/1578
https://github.com/apache/cloudstack/pull/1579
https://github.com/apache/cloudstack/pull/1580
https://github.com/apache/cloudstack/pull/1452

Moreover, we have restructured and extended the documentation with some screen-shots.

**Comment by prashanthvarma** [comment]
@rhtyd @karuturi Please do review this cloudstack-docs PR, which includes changes to the Nuage VSP Plugin documentation for ACS 4.10 release.

**Comment by rhtyd** [comment]
LGTM thanks. /cc @karuturi we can merge this.

**Comment by prashanthvarma** [comment]
@rhtyd @karuturi @krissterckx Additionally, added a section on how to run The Nuage VSP Plugin specific Marvin tests.

You can merge this PR as it is complete now.

**Comment by prashanthvarma** [comment]
@rhtyd @karuturi Can we please merge this ?

**Comment by prashanthvarma** [comment]
@rhtyd @karuturi Can we please merge this now that 4.10 is out  ?

**Comment by swill** [comment]
LGTM.  Maybe we wait until the official announcement of 4.10 goes out, but I think that is just semantics.

**Comment by rhtyd** [comment]
LGTM, merged since 4.10.0.0 is voted and 4.10 branch is cut.

**Pull request merged**
